<?php
$this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js');
?>
<div class="hero-unit">
    <?php if ($this->open) : ?>
    <h1>Session: <span class="zf-green" id="timer"><?=$this->runtime?></span></h1>
    <?php else : ?>
    <h1>Session: <span class="zf-red" id="timer"><?=$this->runtime?></span></h1>
    <?php endif; ?>
</div>
<div class="row">
    <div class="span4">
        <h2>Session</h2>
        <?php if ($this->paused) : ?>
            <p><a href="/index/split?type=resume">Resume Session</a></p>
        <?php endif; ?>
        <?php if (!$this->open && !$this->paused) : ?>
            <p><a href="/index/start">Start Session</a></p>
        <?php endif; ?>
        <?php if ($this->open && !$this->paused) : ?>
            <p><a href="/index/split?type=pause">Pause Session</a></p>
        <?php endif; ?>
        <?php if ($this->open || $this->paused) : ?>
            <p><a href="/index/stop">End Session</a></p>
        <?php endif; ?>
    </div>
    <div class="span4">
        <h2>Projects</h2>
        <p>Switch Project</p>
        <p>New Project</p>
    </div>
    <div class="span4">
        <h2>Management</h2>
        <p><a href="/index/sessions">View Logs</a></p>
        <p>Edit Clock</p>
    </div>
</div>
<script type="text/javascript">
var time = $('#timer').text().split(':');

var run = new Date();
run.setUTCHours(parseInt(time[0], 10));
run.setUTCMinutes(parseInt(time[1], 10));
run.setUTCSeconds(parseInt(time[2], 10));

var start = new Date() - run;

var zeropad = function(num) {
    if (num.toString().length <= 1) {
        return "0" + num;
    } else {
        return num;
    }
};

var updateTime = function() {
    var diff = new Date(new Date() - start);
    $('#timer').text(zeropad(diff.getUTCHours())
        + ':' + zeropad(diff.getUTCMinutes())
        + ':' + zeropad(diff.getUTCSeconds()));
    setTimeout(updateTime, 10);
};
</script>

<?php if ($this->open && !$this->paused) : ?>
<script type="text/javascript">
setTimeout(updateTime, 10);
</script>
<?php endif; ?>
